### ISSUE TITLE
Additional Metadata Output specifying images generated

### ISSUE THREAD

**Issue by Nithos** [docker/bake-action#127]
In my bake files I have a small function that is used for tagging. For example it may add a prefix or a suffix to the image name based on some ENV variable that was set. Because of this I don't have a good way to determine the actual tags that were used and pushed that I can then reference in following jobs. I could make a workaround that uses `jq` with the `--print` option to extract it but it would be best if it was part of the `metadata` output of the workflow.

Actual:
Meta file currently outputs:
- attributes and labels for the image
- platform used
- sources used
- target name used

Desired:
- additionally output the fully qualified image name that was generated i.e `ghcr.io/foo/my_image:123` or at the very least the tag and version (i.e `my_image:123`)

**Comment by crazy-max** [comment]
> would be best if it was part of the `metadata` output of the workflow.

We can't hijack the `metadata` output. It is part of the build UX: https://docs.docker.com/engine/reference/commandline/buildx_build/#metadata-file

> Meta file currently outputs:
>     * attributes and labels for the image
>     * platform used
>     * sources used
>     * target name used

I guess you mean `containerimage.buildinfo`. If so, this is buildinfo which is deprecated and will be removed in the next BuildKit release: https://github.com/moby/buildkit/blob/v0.11/docs/buildinfo.md

> * additionally output the fully qualified image name that was generated i.e `ghcr.io/foo/my_image:123` or at the very least the tag and version (i.e `my_image:123`)

Consider using the `metadata-action` to set tags with bake:  https://github.com/docker/metadata-action#bake-definition. Outputs of the metadata action will have the info you need: https://github.com/docker/metadata-action#outputs
