### ISSUE TITLE
Closed connection while exporting cache

### ISSUE THREAD

**Issue by ukalwa** [docker/bake-action#137]
### Behaviour

I got the following error when I ran bake-action with `gha` cache. If I change the cache-from and cache-to to registry backend, it works without any issue. In the bake file, I only build and push a single image with cache mode set to `max`.

```
Error: buildx bake failed with: ERROR: failed to solve: error writing layer blob: Patch
"https://artifactcache.actions.githubusercontent.com/uTgMzyvCdNIjCtee7zrndnvlIB7VknrPTzIh4DDuGWZFAwVhOj/_apis/artifactcache/caches/202": 
read tcp 172.17.0.2:44358->52.219.169.187:443: use of closed network connection
```

#### Steps to reproduce this issue

I think this may be an intermittent issue and might be related to https://github.com/docker/buildx/issues/367

### Configuration

docker version: 20.10.23
Buildx version: v0.10.4
Bake action version: 3.0.1

**Comment by crazy-max** [comment]
Would need repro with workjflow, Dockerfile and [BuildKit logs](https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs) as well.
