### ISSUE TITLE
Bake entitlements for filesystem should be allowed automatically in action

### ISSUE THREAD

**Issue by tonistiigi** [docker/bake-action#269]
In docker/buildx#2796 by default the filesystem access is only allowed within the working directory. I think in CI context this restriction isn't probably important and the default could be to allow fs access everywhere.

@crazy-max lmk if you prefer any more buildx changes to support this.

**Comment by crazy-max** [comment]
> I think in CI context this restriction isn't probably important and the default could be to allow fs access everywhere.

Yes this makes sense as runners are sandboxed on their own.

**Comment by klutchell** [comment]
This `--allow fs=*` flag is no longer injected for buildx versions v0.19.0 and above, and it actually breaks with buildx version [v0.19.2](https://github.com/docker/buildx/releases/tag/v0.19.2) if the files are outside of the working directory.

https://github.com/docker/bake-action/blob/1677316f88b1bf0cd0c944aecfcd53a07280cf8e/src/context.ts#L86-L89

```
Buildx version
  /usr/bin/docker buildx version
  github.com/docker/buildx v0.19.2 1fc5647dc281ca3c2ad5b451aeff2dce84f1dc49
Builder info
Parsing raw definition
  /usr/bin/docker buildx bake --file /home/runner/work/_temp/docker-bake.json --file /home/runner/work/_temp/docker-actions-toolkit-h5qS9X/docker-metadata-action-bake.json --set *.platform=linux/amd64 --set *.cache-to=type=gha,mode=max,scope=balena-push-env-linux/amd64 --set *.cache-from=type=gha,scope=balena-push-env-linux/amd64 --set *.cache-from=ghcr.io/balena-os/balena-yocto-scripts:master-balena-push-env --set *.cache-from=ghcr.io/balena-os/balena-yocto-scripts:3b2fd8bd993136ce86724c0ada6f47058bd34592-balena-push-env --set *.cache-from=ghcr.io/balena-os/balena-yocto-scripts:build-3b2fd8bd993136ce86724c0ada6f47058bd34592-balena-push-env --set *.cache-from=ghcr.io/balena-os/balena-yocto-scripts:build-ryan-fix-ami-balena-push-env --set *.cache-from=ghcr.io/balena-os/balena-yocto-scripts:latest-balena-push-env --set *.cache-from= --set *.cache-from= --set *.cache-from= --load --provenance false --print balena-push-env
  #1 [internal] load local bake definitions
  #1 reading /home/runner/work/_temp/docker-bake.json 342B / 342B done
  #1 reading /home/runner/work/_temp/docker-actions-toolkit-h5qS9X/docker-metadata-action-bake.json 1.86kB / 1.86kB done
  #1 DONE 0.0s
  ERROR: EOF
```

**Comment by crazy-max** [comment]
@klutchell Do you have a link to your repo so we can look at logs?

**Comment by klutchell** [comment]
Of course, are you able to view the logs at this link?
https://github.com/product-os/flowzone/actions/runs/12306927602/job/34349651093
